### ISSUE TITLE
 found character 	'\t' that cannot start any token while scanning for the next token at line

### ISSUE THREAD

**Issue by skull-squadron** [ruby/psych#136]
Under JRuby 1.7.3 on Heroku:

``` shell
-----> Precompiling assets
       /tmp/build_1nu0be4ptqybj/jruby/bin/jruby bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets
       rake aborted!
       (<unknown>): found character     '\t' that cannot start any token while scanning for the next token at line 43 column 8
       org/jruby/ext/psych/PsychParser.java:221:in `parse'
       /tmp/build_1nu0be4ptqybj/vendor/bundle/jruby/1.9/gems/rails_config-0.3.2/lib/rails_config/sources/yaml_source.rb:17:in `load'
       /tmp/build_1nu0be4ptqybj/vendor/bundle/jruby/1.9/gems/rails_config-0.3.2/lib/rails_config/options.rb:23:in `reload!'
       org/jruby/RubyArray.java:1613:in `each'
       /tmp/build_1nu0be4ptqybj/vendor/bundle/jruby/1.9/gems/rails_config-0.3.2/lib/rails_config/options.rb:22:in `reload!'
       /tmp/build_1nu0be4ptqybj/vendor/bundle/jruby/1.9/gems/rails_config-0.3.2/lib/rails_config.rb:30:in `load_files'
       /tmp/build_1nu0be4ptqybj/vendor/bundle/jruby/1.9/gems/rails_config-0.3.2/lib/rails_config.rb:37:in `load_and_set_settings'
       /tmp/build_1nu0be4ptqybj/vendor/bundle/jruby/1.9/gems/rails_config-0.3.2/lib/rails_config/integration/rails.rb:22:in `Railtie'
       org/jruby/RubyBasicObject.java:1738:in `instance_exec'
       /tmp/build_1nu0be4ptqybj/vendor/bundle/jruby/1.9/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `run'
       /tmp/build_1nu0be4ptqybj/vendor/bundle/jruby/1.9/gems/railties-3.2.13/lib/rails/initializable.rb:55:in `run_initializers'
       org/jruby/RubyArray.java:1613:in `each'
       /tmp/build_1nu0be4ptqybj/vendor/bundle/jruby/1.9/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `run_initializers'
       /tmp/build_1nu0be4ptqybj/vendor/bundle/jruby/1.9/gems/railties-3.2.13/lib/rails/application.rb:136:in `initialize!'
       org/jruby/RubyBasicObject.java:1677:in `__send__'
       org/jruby/RubyKernel.java:2103:in `send'
       /tmp/build_1nu0be4ptqybj/vendor/bundle/jruby/1.9/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
       /tmp/build_1nu0be4ptqybj/config/environment.rb:5:in `(root)'
       org/jruby/RubyKernel.java:1027:in `require'
       /tmp/build_1nu0be4ptqybj/vendor/bundle/jruby/1.9/gems/railties-3.2.13/lib/rails/application.rb:1:in `(root)'
       /tmp/build_1nu0be4ptqybj/vendor/bundle/jruby/1.9/gems/railties-3.2.13/lib/rails/application.rb:103:in `require_environment!'
       org/jruby/RubyProc.java:249:in `call'
       /tmp/build_1nu0be4ptqybj/vendor/bundle/jruby/1.9/gems/railties-3.2.13/lib/rails/application.rb:297:in `initialize_tasks'
       org/jruby/RubyArray.java:1613:in `each'
       org/jruby/RubyProc.java:249:in `call'
       /tmp/build_1nu0be4ptqybj/vendor/bundle/jruby/1.9/gems/actionpack-3.2.13/lib/sprockets/assets.rake:93:in `(root)'
       org/jruby/RubyArray.java:1613:in `each'
       org/jruby/RubyArray.java:1613:in `each'
       org/jruby/RubyProc.java:249:in `call'
       /tmp/build_1nu0be4ptqybj/vendor/bundle/jruby/1.9/gems/actionpack-3.2.13/lib/sprockets/assets.rake:60:in `(root)'
       org/jruby/RubyArray.java:1613:in `each'
       org/jruby/RubyArray.java:1613:in `each'
       org/jruby/RubyKernel.java:1046:in `load'
       Tasks: TOP => environment
       (See full trace by running task with --trace)
       rake aborted!
       Command failed with status (1): [/tmp/build_1nu0be4ptqybj/jruby/bin/jruby b...]
       org/jruby/RubyProc.java:249:in `call'
       /tmp/build_1nu0be4ptqybj/vendor/bundle/jruby/1.9/gems/actionpack-3.2.13/lib/sprockets/assets.rake:12:in `ruby_rake_task'
       /tmp/build_1nu0be4ptqybj/vendor/bundle/jruby/1.9/gems/actionpack-3.2.13/lib/sprockets/assets.rake:21:in `invoke_or_reboot_rake_task'
       /tmp/build_1nu0be4ptqybj/vendor/bundle/jruby/1.9/gems/actionpack-3.2.13/lib/sprockets/assets.rake:29:in `(root)'
       org/jruby/RubyProc.java:249:in `call'
       org/jruby/RubyArray.java:1613:in `each'
       org/jruby/RubyArray.java:1613:in `each'
       org/jruby/RubyKernel.java:1046:in `load'
       Tasks: TOP => assets:precompile
       (See full trace by running task with --trace)
-----> Discovering process types
       Procfile declares types -> web
```

**Comment by vikash1986** [comment]
@tenderlove : This helped me to short this issue as well. Thanks

**Comment by zachmiller1** [comment]
Thank you so much!

**Comment by weimeidsg** [comment]
Thank so much!!!!!

**Comment by sweetppro** [comment]
thanks!

**Comment by ChristyAoko** [comment]
Thanks

**Comment by psecto** [comment]
Thanks !

**Comment by danydiasd** [comment]
Thanks.

**Comment by ScioTechnology** [comment]
Thanks man

**Comment by txlaijava** [comment]
thanks

**Comment by Bicoid** [comment]
thanks!  Now I know!

**Comment by DanTsion** [comment]
Thanks !

**Comment by lujinzhong** [comment]
thank you

**Comment by daniaalsaeed** [comment]
Many thanks

**Comment by grandmaestr** [comment]
Thanks!

**Comment by mmasoudih** [comment]
thanks!

**Comment by fabianoGDB** [comment]
Thanks!

**Comment by oscarnevarezleal** [comment]
Appreciation forever

**Comment by gkarun** [comment]
thanks!

**Comment by PengfeiM** [comment]
thx
