### ISSUE TITLE
ArgumentError: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by azraai** [ruby/psych#139]
Hi.

I was trying to solve this problem for quite sometimes.
There error only happened on my production server but not my development machine with same data.

Here is my backtrace.

```
vendor/bundle/ruby/1.9.1/gems/psych-1.3.4/lib/psych/visitors/yaml_tree.rb:225:in `count'
vendor/bundle/ruby/1.9.1/gems/psych-1.3.4/lib/psych/visitors/yaml_tree.rb:225:in `binary?'
vendor/bundle/ruby/1.9.1/gems/psych-1.3.4/lib/psych/visitors/yaml_tree.rb:234:in `visit_String'
vendor/bundle/ruby/1.9.1/gems/psych-1.3.4/lib/psych/visitors/yaml_tree.rb:103:in `accept'
vendor/bundle/ruby/1.9.1/gems/psych-1.3.4/lib/psych/visitors/yaml_tree.rb:293:in `block in visit_Hash'
vendor/bundle/ruby/1.9.1/gems/psych-1.3.4/lib/psych/visitors/yaml_tree.rb:291:in `each'
vendor/bundle/ruby/1.9.1/gems/psych-1.3.4/lib/psych/visitors/yaml_tree.rb:291:in `visit_Hash'
vendor/bundle/ruby/1.9.1/gems/psych-1.3.4/lib/psych/visitors/yaml_tree.rb:103:in `accept'
vendor/bundle/ruby/1.9.1/gems/psych-1.3.4/lib/psych/visitors/yaml_tree.rb:67:in `push'
vendor/bundle/ruby/1.9.1/gems/psych-1.3.4/lib/psych.rb:242:in `dump'
vendor/bundle/ruby/1.9.1/gems/psych-1.3.4/lib/psych/core_ext.rb:14:in `psych_to_yaml'
vendor/bundle/ruby/1.9.1/gems/paper_trail-2.6.3/lib/paper_trail/has_paper_trail.rb:213:in `object_to_string'
vendor/bundle/ruby/1.9.1/gems/paper_trail-2.6.3/lib/paper_trail/has_paper_trail.rb:160:in `record_update'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:407:in `_run__3320779173298705941__update__4036001397031892802__callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_update_callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/callbacks.rb:272:in `update'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/persistence.rb:348:in `create_or_update'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/callbacks.rb:264:in `block in create_or_update'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:469:in `_run__3320779173298705941__save__4036001397031892802__callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/callbacks.rb:264:in `create_or_update'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/persistence.rb:84:in `save'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/validations.rb:50:in `save'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/attribute_methods/dirty.rb:22:in `save'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/transactions.rb:259:in `block (2 levels) in save'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/transactions.rb:208:in `transaction'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/transactions.rb:259:in `block in save'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/transactions.rb:270:in `rollback_active_record_state!'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/transactions.rb:258:in `save'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/persistence.rb:217:in `block in update_attributes'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/transactions.rb:208:in `transaction'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/persistence.rb:215:in `update_attributes'
vendor/bundle/ruby/1.9.1/gems/inherited_resources-1.3.1/lib/inherited_resources/base_helpers.rb:78:in `update_resource'
vendor/bundle/ruby/1.9.1/gems/inherited_resources-1.3.1/lib/inherited_resources/actions.rb:45:in `update'
app/controllers/admin/documents_controller.rb:22:in `update'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/abstract_controller/base.rb:167:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_controller/metal/rendering.rb:10:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:480:in `_run__1049249814261778128__process_action__2680946908806648429__callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/abstract_controller/callbacks.rb:17:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_controller/metal/rescue.rb:29:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/notifications.rb:123:in `block in instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/notifications.rb:123:in `instrument'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/abstract_controller/base.rb:121:in `process'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/abstract_controller/rendering.rb:45:in `process'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_controller/metal.rb:203:in `dispatch'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_controller/metal.rb:246:in `block in action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:73:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:36:in `call'
vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:601:in `call'
vendor/bundle/ruby/1.9.1/gems/omniauth-1.1.1/lib/omniauth/strategy.rb:177:in `call!'
vendor/bundle/ruby/1.9.1/gems/omniauth-1.1.1/lib/omniauth/strategy.rb:157:in `call'
vendor/bundle/ruby/1.9.1/gems/omniauth-1.1.1/lib/omniauth/builder.rb:48:in `call'
vendor/bundle/ruby/1.9.1/gems/warden-1.2.1/lib/warden/manager.rb:35:in `block in call'
vendor/bundle/ruby/1.9.1/gems/warden-1.2.1/lib/warden/manager.rb:34:in `catch'
vendor/bundle/ruby/1.9.1/gems/warden-1.2.1/lib/warden/manager.rb:34:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.3/lib/rack/etag.rb:23:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.3/lib/rack/conditionalget.rb:35:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_dispatch/middleware/head.rb:14:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_dispatch/middleware/flash.rb:242:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.3/lib/rack/session/abstract/id.rb:210:in `context'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.3/lib/rack/session/abstract/id.rb:205:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_dispatch/middleware/cookies.rb:341:in `call'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/query_cache.rb:64:in `call'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `_run__1212725707803134744__call__4036001397031892802__callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.11/lib/rails/rack/logger.rb:32:in `call_app'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.11/lib/rails/rack/logger.rb:16:in `block in call'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/tagged_logging.rb:22:in `tagged'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.11/lib/rails/rack/logger.rb:16:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_dispatch/middleware/request_id.rb:22:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.3/lib/rack/methodoverride.rb:21:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.3/lib/rack/runtime.rb:17:in `call'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.3/lib/rack/lock.rb:15:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:143:in `pass'
vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:155:in `invalidate'
vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:71:in `call!'
vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.11/lib/rails/engine.rb:479:in `call'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.11/lib/rails/application.rb:223:in `call'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.11/lib/rails/railtie/configurable.rb:30:in `method_missing'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_request_handler.rb:516:in `accept_and_process_next_request'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `block in handle_spawn_application'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/utils.rb:470:in `safe_fork'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:180:in `start'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:219:in `block (2 levels) in spawn_rails_application'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:214:in `block in spawn_rails_application'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
<internal:prelude>:10:in `synchronize'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/passenger-3.0.19/helper-scripts/passenger-spawn-server:99:in `<main>'

And the parameters

{"utf8"=>"✓",
 "_method"=>"put",
 "authenticity_token"=>"ZYhcdq9fgFjbKONgUS8mjTn3YuiyQFHBTF6LTxlQfGA=",
 "document"=>{"title"=>"Vehicle murabaha transactions in Middle Eastern countries.",
 "alternative_title"=>"",
 "description"=>"Murabaha is a particular kind of sale where seller expressly mentions the cost it has incurred on purchase of the Asset(s) to be sold and sells it to another person by adding some profit,
 which is known to buyer. Murabaha finance is not a loan given on interest,
 it is a sale of Asset(s) for cash/deferred price. It is the obligation of the seller to disclose the cost and profit to the buyer. Murabaha transaction can either be a cash sale (spot payment murabaha) or a credit sale (deferred payment murabaha) or a combination of both. Even though the transactions are widely used in the modern Islamic banking field,
 but the methodology and transactions are having slightly deferred to country to country without changing the core concept of murabaha as per the Maqasid Al Shariah.",
 "category_id"=>"183",
 "related_category_ids"=>["",
 "13"],
 "kind"=>"document",
 "type_id"=>"7",
 "authors_cache"=>"",
 "subjects_cache"=>"",
 "language"=>"English",
 "source"=>"INCEIF",
 "rights"=>"2011. Rahamathulla Theverthodi",
 "pages"=>"1,
2"},
 "commit"=>"Update Document",
 "id"=>"3667"}
```

**Comment by tinynumbers** [comment]
I know this is an old one but I'm having this same issue currently on a Ruby 2.0.0 / Rails 3.2.21 project. 

Here's a simple case to reproduce - run the following in the Rails console:

```ruby
Psych.dump({"STATE"=>"Reykjav\xEDk"})
```

Here's the stack trace:

```
ArgumentError: invalid byte sequence in UTF-8
  from /Users/dev/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/psych/visitors/yaml_tree.rb:250:in `count'
  from /Users/dev/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/psych/visitors/yaml_tree.rb:250:in `binary?'
  from /Users/dev/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/psych/visitors/yaml_tree.rb:262:in `visit_String'
  from /Users/dev/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/psych/visitors/yaml_tree.rb:128:in `accept'
  from /Users/dev/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/psych/visitors/yaml_tree.rb:324:in `block in visit_Hash'
  from /Users/dev/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/psych/visitors/yaml_tree.rb:322:in `each'
  from /Users/dev/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/psych/visitors/yaml_tree.rb:322:in `visit_Hash'
  from /Users/dev/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/psych/visitors/yaml_tree.rb:128:in `accept'
  from /Users/dev/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/psych/visitors/yaml_tree.rb:92:in `push'
  from /Users/dev/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/psych.rb:244:in `dump'
  from (irb):7
```
