### ISSUE TITLE
.to_yaml fails when tempfile is an instance variable

### ISSUE THREAD

**Issue by sdjespersen** [ruby/psych#176]
Here's a quick script to reproduce the issue:

``` ruby
require 'tempfile'
require 'psych'

class Foo 
  def initialize
    @tf = Tempfile.new('foo')
  end 
end 

f = Foo.new
puts f.to_yaml
```

Then `ruby foo.rb` produces the following stacktrace:

```
/Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:26:in `block in initialize': undefined method `name' for nil:NilClass (NoMethodError)
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:28:in `yield'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:28:in `default'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:28:in `block in initialize'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:28:in `yield'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:28:in `default'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:28:in `block in initialize'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:28:in `yield'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:28:in `default'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:28:in `block in initialize'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:28:in `yield'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:28:in `default'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:28:in `block in initialize'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:103:in `yield'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:103:in `default'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:103:in `accept'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:449:in `block in dump_ivars'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:447:in `each'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:447:in `dump_ivars'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:125:in `visit_Object'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:103:in `accept'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:67:in `push'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych.rb:242:in `dump'
  from /Users/me/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/psych/core_ext.rb:14:in `psych_to_yaml'
  from foo.rb:11:in `<main>'
```

Is there a reason I shouldn't be using `.to_yaml` with such an object? Or is this a legitimate bug?

**Comment by salex** [comment]
Don't know if his is related, but I tried to serialize a hash created from and Icalandar event and got the error: `NoMethodError: undefined method `name' for nil:NilClass`

Debugging the problem I found this post. After a little digging I found my problem was that what I though was a text field in the hash had a class of `Icalendar::Values::Text'.  

I can't remember the exact circumstance, but several publicly available icalanders (Apple's holidays) had some character sequences that was throwing an encoding error. I ended up having to force encoding on those text fields:

    e.summary = e.summary.force_encoding("UTF-8")

That fix to a bug in (Icalendar,?) gave me the undefined method error. There is also a new issue that reference forced encoding. I fixed my problem by converting the fields to_s before serializing since I assume psych can't account for every gem specific class. The hash I created worked fine in displaying the calendar, but I decided to serialize and save it and ran into this problem.

**Comment by hsbt** [comment]
Dumping an object with a Tempfile instance variable no longer raises on current releases. Closing as resolved.
