### ISSUE TITLE
Ruby 2.3.0 - cannot load OpenStructs

### ISSUE THREAD

**Issue by Timo614** [ruby/psych#263]
Seems to be either psych or I guess perhaps some changes to ostruct made in the ruby 2.3.0 branch of ruby. The underlying code for ostruct has changed quite a bit it looks like so not really sure which could be at fault here and I'm not familiar with psych or ostruct's code. Let me know if psych isn't causing this and I can file an issue with ruby core. Not entirely sure what's wrong though but can reproduce consistently so hoping someone with a better understanding of how psych works can shed some light on it to tell me if it's likely an issue with psych itself or unrelated.

This came up because I was trying to serialize OpenStruct data in a rails model which previously worked but stopped working after I tried updating the application to ruby 2.3.0. 

https://github.com/ruby/ruby/blob/v2_2_4/lib/ostruct.rb
https://github.com/ruby/ruby/blob/v2_3_0/lib/ostruct.rb#L174

```
rvm use 2.3.0
irb
require 'psych'
require 'ostruct'
Psych.load("--- !ruby/object:OpenStruct
table:
  :object: !ruby/object:OpenStruct
    table:
      :id: test")
```

Causes:

```
NoMethodError: undefined method `key?' for nil:NilClass
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/ostruct.rb:176:in `respond_to_missing?'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:381:in `respond_to?'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:381:in `init_with'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:374:in `revive'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:208:in `visit_Psych_Nodes_Mapping'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in `each'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in `each_slice'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in `revive_hash'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
... 1 levels...
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in `each'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in `each_slice'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in `revive_hash'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:374:in `revive'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:208:in `visit_Psych_Nodes_Mapping'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych/nodes/node.rb:38:in `to_ruby'
  from /Users/tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:253:in `load'
  from (irb):4
```

Using 2.2.4

```
rvm use 2.2.4
irb
require 'psych'
require 'ostruct'
Psych.load("--- !ruby/object:OpenStruct
table:
  :object: !ruby/object:OpenStruct
    table:
      :id: test")
```

```
 => #<OpenStruct object=#<OpenStruct id="test">>
```

**Comment by sublimecoder** [comment]
I have the same issue I can dump a ostruct to yaml but loading it barfs in the manner describe above.

**Comment by virtualfunction** [comment]
FYI to hack round this until the next ruby release, you can nab the code from https://github.com/ruby/ruby/blob/trunk/lib/ostruct.rb - or monkey patch it (I think the changes on the 29th fixes this)

**Comment by hsbt** [comment]
Ruby 2.3 is already EOL. There is no chance to backport for them.
