### ISSUE TITLE
psych parse error when using multi-line environment variables on Heroku

### ISSUE THREAD

**Issue by hmistry** [ruby/psych#308]
I get a psych parse error when I use multi-line variables on Heroku causing my rails app to fail starting up making it hard to debug. The reason for using multi-line variables is to store my super_secret_certificate.pem file as I do not want to check it into my git repo and Heroku does not allow any files other than what's in the repo.

If I change the environment variable to a single line, it works fine. The config/secrets.yml file is simply reading from the env variable.

SO post where this solution seems to work for others earlier: http://stackoverflow.com/questions/6942600/multi-line-config-variables-in-heroku

Any thoughts on how to resolve this?

Using Ruby 2.3.0, Rails 5.0.0, gem 2.5.1, psych 2.0.17.
```
/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:377:in `parse': (<unknown>): could not find expected ':' while scanning a simple key at line 29 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:252:in `load'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/application.rb:391:in `secrets'
	from /app/config/initializers/carrierwave.rb:8:in `block in <top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/gems/carrierwave-0.11.2/lib/carrierwave/uploader/configuration.rb:118:in `configure'
	from /app/vendor/bundle/ruby/2.3.0/gems/carrierwave-0.11.2/lib/carrierwave.rb:14:in `configure'
	from /app/config/initializers/carrierwave.rb:2:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `block in load'
	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:648:in `block in load_config_initializer'
	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications.rb:166:in `instrument'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:647:in `load_config_initializer'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:611:in `each'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:611:in `block in <class:Engine>'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:44:in `each'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:415:in `call'
	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:54:in `run_initializers'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/application.rb:352:in `initialize!'
	from /app/config/environment.rb:7:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/gems/skylight-1.0.0/lib/skylight/probes.rb:81:in `require'
	from /app/vendor/bundle/ruby/2.3.0/gems/skylight-1.0.0/lib/skylight/probes.rb:81:in `require'
	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/application.rb:328:in `require_environment!'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:157:in `require_application_and_environment!'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:77:in `console'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
	from /app/bin/rails:4:in `require'
	from /app/bin/rails:4:in `<main>'

```

**Comment by tenderlove** [comment]
There isn't anything I can do to resolve this in Psych.  I believe Heroku is using ERB to generate YAML, so they need to ensure that whatever is returned from ERB is correctly encoded to YAML.  /cc @hone

**Comment by hmistry** [comment]
Appreciate the response.

**Comment by schneems** [comment]
@hmistry did you open a support ticket with Heroku? I've not seen this issue before. If not, could you open one up at https://help.heroku.com search for "yaml multi line env var", open a ticket and then let me know the ticket number so I can take a look? 

You can link to this issue in the ticket.

**Comment by hmistry** [comment]
@schneems Really nice to see this proactive-ness! Thank you.
Yes I did contact support and they found a work around for me. 
Details here: `Ticket #444880 - Adding multi-line Environment variable causes app to crash`.

**Comment by dzacarias** [comment]
@hmistry What was the workaround? (I believe that tickets are private to each account)

**Comment by hmistry** [comment]
@dzacarias 
1. Create a .profile file in your app that will write the multi-line env variable to a file stored in my app container in Heroku on boot up.
```
echo "$EXAMPLE_CERT_KEY" > ./example_cert_key.pem
```

2. Change the secrets.yml to read from the file instead (in my case I did it in the class of interest instead).
```
cert = File.read(File.join(Rails.root, "example_cert_key.pem"))
```

**Comment by dzacarias** [comment]
@hmistry Thanks, will try!

**Comment by smaximov** [comment]
I had the same problem and solved it differently. The trick is to manually indent the lines of the multi-line value when inserting it into the template so it would be valid YAML after ERB processing. 

You can use the Active Support `String#indent` extension or roll your own (`gsub(/^/, ' ' * 8)`, for example):

``` yml
production:
  aws:
    cf:
      signer_private_key: |-
<%= ENV.fetch('TMP_AWS_CF_SIGNER_PRIVATE_KEY').indent(8) %>
```

**Comment by LesterKim** [comment]
> I had the same problem and solved it differently. The trick is to manually indent the lines of the multi-line value when inserting it into the template so it would be valid YAML after ERB processing.
> 
> You can use the Active Support `String#indent` extension or roll your own (`gsub(/^/, ' ' * 8)`, for example):
> 
> ```yaml
> production:
>   aws:
>     cf:
>       signer_private_key: |-
> <%= ENV.fetch('TMP_AWS_CF_SIGNER_PRIVATE_KEY').indent(8) %>
> ```

@smaximov Thank you! I really appreciate your help.
