### ISSUE TITLE
Loading a YAML file which contains a date fails

### ISSUE THREAD

**Issue by tanner-bruce** [ruby/psych#362]
Simplest way to reproduce:
`YAML.safe_load('expiry: 2018-02-08 03:32:36')`

results in

```
Traceback (most recent call last):
       16: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/visitor.rb:6:in `accept'
       15: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/visitor.rb:16:in `visit'
       14: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
       13: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/to_ruby.rb:336:in `revive_hash'
       12: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/to_ruby.rb:336:in `each_slice'
       11: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/to_ruby.rb:336:in `each'
       10: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
        9: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/to_ruby.rb:32:in `accept'
        8: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/visitor.rb:6:in `accept'
        7: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/visitor.rb:16:in `visit'
        6: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/to_ruby.rb:123:in `visit_Psych_Nodes_Scalar'
        5: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/to_ruby.rb:60:in `deserialize'
        4: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/scalar_scanner.rb:62:in `tokenize'
        3: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/scalar_scanner.rb:123:in `parse_time'
        2: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/class_loader.rb:28:in `load'
        1: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/class_loader.rb:97:in `find'
Psych::DisallowedClass (Tried to load unspecified class: Time)
```

**Comment by cben** [comment]
Seems this is not a bug, it's the documented default.
`Psych.safe_load('expiry: 2018-02-08 03:32:36', [Date, Time])` works.

- [x] https://ruby-doc.org/stdlib/libdoc/psych/rdoc/Psych.html#safe_load-method clearly documents the default allowed types, ability to whitelist, and gives `[Date]` as example of whitelist :clap:

[P.S. for future readers finding this: see also #262 for explanation how *some* date-like inputs do get parsed, as strings — if they're not valid dates]

**Comment by tanner-bruce** [comment]
Thanks @cben!
