### ISSUE TITLE
Psych.load --- AWS Cloudformation -- @Fn::Join' is not allowed as an instance variable name

### ISSUE THREAD

**Issue by rainmanh** [ruby/psych#363]
Hi,

Currently using the following version:
ruby: ruby 2.2.10p489 
gem : (3.0.2, default: 2.0.8.1) (tried with both)

I am simply loading an AWS  CloudFormation and it fails at the following part:

```
<snip>
LaunchConfig:
  Type: 'AWS::AutoScaling::LaunchConfiguration'
  Properties:
    AssociatePublicIpAddress: 'true'
    ImageId: !Ref OutboundProxyImageId
    InstanceType: !Ref OutboundProxyInstanceType
    SecurityGroups:
      - !Ref OutboundProxySecurityGroupId
      - !Ref AwsApiSecurityGroupId
    IamInstanceProfile: !Ref OutboundProxyInstanceProfile
    InstanceMonitoring: 'false'
    KeyName: tester
    UserData: !Base64
      'Fn::Join':
        - ''
        - - |
            #!/bin/bash
          - |
            set -x
          - >
            exec > > run_script
<snip>
```

I am loading the YAML with a very simple method:

```
      def load_yaml(yaml)
            Psych.load(yaml)
      end
```

I am getting the following error:

```
.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:384:in `instance_variable_set': `@Fn::Join' is not allowed as an instance variable name (NameError)
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:384:in `block in init_with'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:384:in `each'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:384:in `init_with'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:374:in `revive'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:160:in `visit_Psych_Nodes_Mapping'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/visitor.rb:16:in `visit'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:32:in `accept'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:336:in `each'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:336:in `each_slice'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:336:in `revive_hash'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/visitor.rb:16:in `visit'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:32:in `accept'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:336:in `each'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:336:in `each_slice'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:336:in `revive_hash'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/visitor.rb:16:in `visit'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:32:in `accept'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:336:in `each'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:336:in `each_slice'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:336:in `revive_hash'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/visitor.rb:16:in `visit'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:32:in `accept'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:336:in `each'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:336:in `each_slice'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:336:in `revive_hash'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/visitor.rb:16:in `visit'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:32:in `accept'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/visitor.rb:16:in `visit'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:32:in `accept'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych/nodes/node.rb:50:in `to_ruby'
	from /Users/<user>/.rvm/gems/ruby-2.2.10/gems/psych-3.0.2/lib/psych.rb:264:in `load'

```

I have tried , as documented on AWS Cloudformation Docs Different syntax and even trying escapes over **Fn::Join** without any luck .

Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-join.html

```
JSON
{ "Fn::Join" : [ "delimiter", [ comma-delimited list of values ] ] }

YAML
Syntax for the full function name:

Fn::Join: [ delimiter, [ comma-delimited list of values ] ]
Syntax for the short form:

!Join [ delimiter, [ comma-delimited list of values ] ]

```

I can confirm the Cloudformation YAML file work perfectly fine when running manually and executing within AWS, but it's just failing the parsing using Psych.

Would be possible to help with this issue, please? 

I would rather keep using Psych before thinking on refactoring all the code because just a single issue.

Many thanks for all your help

**Comment by rainmanh** [comment]
Hi,

In the end the issue wasn't down to Psych as it was doing the parsing correctly but to a base64 filtering I completely forgot about and which was the culprit on this issue.

Many thanks.
