### ISSUE TITLE
Updating psych to most recent version fails

### ISSUE THREAD

**Issue by fasmat** [ruby/psych#497]
Hi,

I'm trying to update psych to the most recent version and I'm receiving errors:

```
Updating psych
Building native extensions. This could take a while...
ERROR:  Error installing psych:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.7.0/gems/psych-4.0.0/ext/psych
/usr/bin/ruby2.7 -I /usr/lib/ruby/2.7.0 -r ./siteconf20210525-15864-1ftcb9w.rb extconf.rb
checking for yaml.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.7
	--with-libyaml-dir
	--without-libyaml-dir
	--with-libyaml-include
	--without-libyaml-include=${libyaml-dir}/include
	--with-libyaml-lib
	--without-libyaml-lib=${libyaml-dir}/lib
	--enable-bundled-libyaml
	--disable-bundled-libyaml
/usr/lib/ruby/2.7.0/mkmf.rb:471:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/2.7.0/mkmf.rb:613:in `try_cpp'
	from /usr/lib/ruby/2.7.0/mkmf.rb:1177:in `block in find_header'
	from /usr/lib/ruby/2.7.0/mkmf.rb:971:in `block in checking_for'
	from /usr/lib/ruby/2.7.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /usr/lib/ruby/2.7.0/mkmf.rb:331:in `open'
	from /usr/lib/ruby/2.7.0/mkmf.rb:361:in `block in postpone'
	from /usr/lib/ruby/2.7.0/mkmf.rb:331:in `open'
	from /usr/lib/ruby/2.7.0/mkmf.rb:357:in `postpone'
	from /usr/lib/ruby/2.7.0/mkmf.rb:970:in `checking_for'
	from /usr/lib/ruby/2.7.0/mkmf.rb:1176:in `find_header'
	from extconf.rb:10:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.7.0/extensions/x86_64-linux/2.7.0/psych-4.0.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.7.0/gems/psych-4.0.0 for inspection.
```

mkmf.log:
```
"gcc -o conftest -I/usr/include/x86_64-linux-gnu/ruby-2.7.0 -I/usr/include/ruby-2.7.0/ruby/backward -I/usr/include/ruby-2.7.0 -I. -Wdate-time -D_FORTIFY_SOURCE=2   -g -O2 -fdebug-prefix-map=/build/ruby2.7-2E2p8v/ruby2.7-2.7.0=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC conftest.c  -L. -L/usr/lib/x86_64-linux-gnu -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -lruby-2.7  -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */
```

I'm using Ubuntu 20.04 with Ruby 2.7.0 from the official repositories. `yaml.h` is available on my system at `/usr/include/yaml.h` provided by the `libyaml-dev` package.

**Comment by olleolleolle** [comment]
Would `sudo apt-get install build-essential` help?

**Comment by fasmat** [comment]
@olleolleolle ``build-essential`` is installed and up-to-date. ``psych`` is the only gem that fails when installing/updating.

**Comment by olleolleolle** [comment]
@fasmat (These are general diagnostic questions, I hope they're helpful.) Do you have a ruby-dev package variant, with `ruby.h` installed and available? https://packages.ubuntu.com/focal/ruby-dev

**Comment by fasmat** [comment]
@olleolleolle Yes, also installed and up-to-date.

**Comment by fasmat** [comment]
I was not yet able to resolve this issue. Any ideas what else it could be?
