### ISSUE TITLE
Code broken after update to 4.0.0

### ISSUE THREAD

**Issue by maximecb** [ruby/psych#501]
I'm getting errors in two different benchmarks that were previously working after updating to 4.0.0, which is bundled with ruby.

```
.rubies/ruby-yjit/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias': Unknown alias: product-1-var-1 (Psych::BadAlias)
	from /Users/maximecb/.rubies/ruby-yjit/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
	from /Users/maximecb/.rubies/ruby-yjit/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
	from /Users/maximecb/.rubies/ruby-yjit/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/maximecb/.rubies/ruby-yjit/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `block in register_empty'
	from /Users/maximecb/.rubies/ruby-yjit/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `each'
	from /Users/maximecb/.rubies/ruby-yjit/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `register_empty'
	from /Users/maximecb/.rubies/ruby-yjit/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:146:in `visit_Psych_Nodes_Sequence'
```

This is problematic. If someone could advise on how to go to lock to a previous version of the psych gem in the meantime, that would be useful.

Also paging @tenderlove. This is separate from the other failure we had previously identified.

**Comment by developius** [comment]
Yeah. It's breaking aliases and symbols. @maximecb I've added this to my `Gemfile` for now:

```rb
gem 'psych', '~> 3'
```

**Comment by olleolleolle** [comment]
Would it be posible to .use unsafe_load_file or .unsafe_load in the meantime, @maximecb? 

```
09:12:06 >> YAML.unsafe_load("---\n  :olle: &moniker that is me\n  :they: hello\n  :me: *moniker\n")
=> {:olle=>"that is me", :they=>"hello", :me=>"that is me"}
09:12:13 >> YAML.load("---\n  :olle: &moniker that is me\n  :they: hello\n  :me: *moniker\n")
Psych::BadAlias: Unknown alias: moniker
from /home/olle/tmp/devbox/gems/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias'
```
