### ISSUE TITLE
Tried to load unspecified class: HTTP::Cookie (Psych::DisallowedClass)

### ISSUE THREAD

**Issue by igoriuz** [ruby/psych#503]
Using [fastlane](https://github.com/fastlane/fastlane/issues/18768) with the latest psych version seems broken. It might have to do with the recently added safe-dump feature.

Downgrading from 4.0.0 to 3.3.0 works again. (Haven't tried versions inbetween).

```
/Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/class_loader.rb:99:in `find': \e[31m[!] Tried to load unspecified class: HTTP::Cookie\e[0m (Psych::DisallowedClass)
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/class_loader.rb:28:in `load'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:424:in `resolve_class'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:213:in `visit_Psych_Nodes_Mapping'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:30:in `visit'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:338:in `block in register_empty'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:338:in `each'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:338:in `register_empty'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:146:in `visit_Psych_Nodes_Sequence'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:30:in `visit'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:30:in `visit'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych.rb:334:in `safe_load'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych.rb:369:in `load'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/http-cookie-1.0.3/lib/http/cookie_jar/yaml_saver.rb:24:in `load'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:325:in `block in load'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:324:in `open'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:324:in `load'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/client.rb:609:in `load_session_from_env'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/client.rb:441:in `send_shared_login_request'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/client.rb:808:in `do_login'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/client.rb:393:in `login'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/client.rb:355:in `login'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/connect_api/client.rb:56:in `login'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/actions/download_dsyms.rb:18:in `run'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:60:in `block (2 levels) in parsing_binding'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/bin/fastlane:23:in `<top (required)>'
	from /Users/r2d2/.rbenv/versions/3.0.1/bin/fastlane:23:in `load'
	from /Users/r2d2/.rbenv/versions/3.0.1/bin/fastlane:23:in `<main>'
/Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/class_loader.rb:99:in `find': Tried to load unspecified class: HTTP::Cookie (Psych::DisallowedClass)
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/class_loader.rb:28:in `load'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:424:in `resolve_class'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:213:in `visit_Psych_Nodes_Mapping'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:30:in `visit'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:338:in `block in register_empty'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:338:in `each'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:338:in `register_empty'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:146:in `visit_Psych_Nodes_Sequence'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:30:in `visit'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:30:in `visit'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych.rb:334:in `safe_load'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych.rb:369:in `load'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/http-cookie-1.0.3/lib/http/cookie_jar/yaml_saver.rb:24:in `load'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:325:in `block in load'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:324:in `open'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:324:in `load'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/client.rb:609:in `load_session_from_env'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/client.rb:441:in `send_shared_login_request'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/client.rb:808:in `do_login'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/client.rb:393:in `login'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/client.rb:355:in `login'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/connect_api/client.rb:56:in `login'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/actions/download_dsyms.rb:18:in `run'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:60:in `block (2 levels) in parsing_binding'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Users/r2d2/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/fastlane-2.184.1/bin/fastlane:23:in `<top (required)>'
	from /Users/r2d2/.rbenv/versions/3.0.1/bin/fastlane:23:in `load'
	from /Users/r2d2/.rbenv/versions/3.0.1/bin/fastlane:23:in `<main>'
```

**Comment by olleolleolle** [comment]
4.0.0 is a major upgrade, due to the backwards-breaking changes.

The release includes an ["unsafe_load"](https://github.com/ruby/psych/commit/cb50aa8d3fb8be01897becff77b4922b12a0ab4c), which could be used in the gem which is raising the error by calling YAML.load 
https://github.com/sparklemotion/http-cookie/blob/master/lib/http/cookie_jar/yaml_saver.rb#L24

**Comment by developius** [comment]
Also see #501, #490 & #489

**Comment by igoriuz** [comment]
First of all: Thank you guys for your fast and helpful comments. I don't quite understand changing existing method bodies without changing any functionality at all. Wouldn't it be better just to deprecate methods instead of... breaking a lot of gems? ;) A meaningful warning with how to do it better would've had less impact to the whole ecosystem.

Don't get me wrong, i'm a friend of security by design.

**Comment by olleolleolle** [comment]
Upstream has been made compatible, by having a safe_load code-path: https://github.com/sparklemotion/http-cookie/pull/34

**Comment by igoriuz** [comment]
[Merged and released](https://github.com/sparklemotion/http-cookie/pull/34#issuecomment-855686693). Thank you @olleolleolle for your commitment :)

**Comment by baraidrissa** [comment]
if your application uses Symbol and Time in serialized data, you can add Symbol and Time to the allowed list as follows:

`config.active_record.yaml_column_permitted_classes = [Symbol, Date, Time]`
