### ISSUE TITLE
Support for M1 (ARM) Macs?

### ISSUE THREAD

**Issue by igoriuz** [ruby/psych#505]
Tried installing psych on M1 but it seems not to work. I've installed libyaml and reinstalled ruby via rbenv.

Any ideas?

```
ig-11@IG-11s-Mac-mini ~ % gem install psych
/Users/ig-11/.rbenv/versions/3.0.1/lib/ruby/3.0.0/yaml.rb:3: warning: It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
<internal:/Users/ig-11/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': dlopen(/Users/ig-11/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.1/lib/psych.bundle, 9): no suitable image found.  Did find: (LoadError)
	/Users/ig-11/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.1/lib/psych.bundle: mach-o, but wrong architecture
	/Users/ig-11/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.1/lib/psych.bundle: mach-o, but wrong architecture - /Users/ig-11/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.1/lib/psych.bundle
	from <internal:/Users/ig-11/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/ig-11/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.1/lib/psych.rb:13:in `<top (required)>'
	from <internal:/Users/ig-11/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/ig-11/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/ig-11/.rbenv/versions/3.0.1/lib/ruby/3.0.0/yaml.rb:4:in `<top (required)>'
	from <internal:/Users/ig-11/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/ig-11/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/ig-11/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems.rb:641:in `load_yaml'
	from /Users/ig-11/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/config_file.rb:345:in `load_file'
	from /Users/ig-11/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/config_file.rb:189:in `initialize'
	from /Users/ig-11/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/gem_runner.rb:73:in `new'
	from /Users/ig-11/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/gem_runner.rb:73:in `do_configuration'
	from /Users/ig-11/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/gem_runner.rb:38:in `run'
	from /Users/ig-11/.rbenv/versions/3.0.1/bin/gem:21:in `<main>'
```

**Comment by hsbt** [comment]
It depends your environments that are x86 via Rosseta2, arm, or mixing them. At least, I could install psych-4.0.1 with arm arch.

```
hsbt@ringo ~ % ruby -v
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [arm64-darwin20]
hsbt@ringo ~ % gem i psych
Fetching psych-4.0.1.gem
Building native extensions. This could take a while...
Successfully installed psych-4.0.1
1 gem installed
```

**Comment by igoriuz** [comment]
The M1 Mac Mini is freshly installed with the exact version like you have @hsbt.. not quite sure why it doesn't work. How can i serve better diagnostics?
