### ISSUE TITLE
ruby-1.9.3-p0/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:217:in `merge!': can't convert nil into Hash 

### ISSUE THREAD

**Issue by dfischer** [ruby/psych#70]
I was trying to install Mongoid on a new Rails app and I got the following stack trace:

```
rails g mongoid:config
Sass is in the process of being separated from Haml,
and will no longer be bundled at all in Haml 3.2.0.
Please install the 'sass' gem if you want to use Sass.

/Users/Armageddon/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:217:in `merge!': can't convert nil into Hash (TypeError)
	from /Users/Armageddon/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:217:in `block in revive_hash'
	from /Users/Armageddon/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:211:in `each'
	from /Users/Armageddon/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:211:in `each_slice'
	from /Users/Armageddon/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:211:in `revive_hash'
	from /Users/Armageddon/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:123:in `visit_Psych_Nodes_Mapping'
	from /Users/Armageddon/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych/visitors/visitor.rb:15:in `visit'
	from /Users/Armageddon/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych/visitors/visitor.rb:5:in `accept'
	from /Users/Armageddon/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:16:in `accept'
	from /Users/Armageddon/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:226:in `block in revive_hash'
	from /Users/Armageddon/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:211:in `each'
	from /Users/Armageddon/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:211:in `each_slice'
	from /Users/Armageddon/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:211:in `revive_hash'
	from /Users/Armageddon/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:123:in `visit_Psych_Nodes_Mapping'
	from /Users/Armageddon/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych/visitors/visitor.rb:15:in `visit'
	from /Users/Armageddon/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych/visitors/visitor.rb:5:in `accept'
	from /Users/Armageddon/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:16:in `accept'
	from /Users/Armageddon/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych/nodes/node.rb:35:in `to_ruby'
	from /Users/Armageddon/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:113:in `load'
	from /Users/Armageddon/.rvm/gems/ruby-1.9.3-p0/gems/mongoid-3.0.1/lib/mongoid/config/environment.rb:40:in `load_yaml'
	from /Users/Armageddon/.rvm/gems/ruby-1.9.3-p0/gems/mongoid-3.0.1/lib/mongoid/config.rb:69:in `load!'
	from /Users/Armageddon/.rvm/gems/ruby-1.9.3-p0/gems/mongoid-3.0.1/lib/mongoid.rb:148:in `load!'
	from /Users/Armageddon/.rvm/gems/ruby-1.9.3-p0/gems/mongoid-3.0.1/lib/mongoid/railtie.rb:81:in `block in <class:Railtie>'
	from /Users/Armageddon/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.6/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/Armageddon/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.6/lib/rails/initializable.rb:30:in `run'
	from /Users/Armageddon/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/Armageddon/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.6/lib/rails/initializable.rb:54:in `each'
	from /Users/Armageddon/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.6/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/Armageddon/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.6/lib/rails/application.rb:136:in `initialize!'
	from /Users/Armageddon/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.6/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /Users/Armageddon/Projects/Business/apollo/myapp/config/environment.rb:5:in `<top (required)>'
	from /Users/Armageddon/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.6/lib/rails/application.rb:103:in `require'
	from /Users/Armageddon/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.6/lib/rails/application.rb:103:in `require_environment!'
	from /Users/Armageddon/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.6/lib/rails/commands.rb:25:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

**Comment by hsbt** [comment]
Ruby 1.9 series is EOL now. If you have this issue with latest version of ruby, Please submit new issue with it version.
